name = "LapeyreRegistry"
uuid = "907be819-33fb-43a5-ba93-44eb55921698"
repo = "http://github.com/jlapeyre/LapeyreRegistry"
description = "Registry for some packages not in the General Registry"

[packages]
08411ca2-877e-473c-bca1-3021299c4a4d = { name = "Rotate", path = "R/Rotate" }
69a6172a-6e93-4cbc-8d73-93c06968df79 = { name = "GraphsExt", path = "G/GraphsExt" }
6dbe6948-1a74-428b-a0c7-b6033448b207 = { name = "StackEnvs", path = "S/StackEnvs" }
6f66f461-bf35-48e1-be20-3c513c87d4ba = { name = "Recamans", path = "R/Recamans" }
76a85e09-bf2a-452f-b9ef-4e204e7481ea = { name = "PirateUtils", path = "P/PirateUtils" }
7c338ca5-b20e-417b-9799-aae6c720705e = { name = "BlockEnums", path = "B/BlockEnums" }
8edef7da-e1b3-479c-b6e4-7e7cac36144b = { name = "IdentityMatrix", path = "I/IdentityMatrix" }
8fd3887d-e730-4110-8d7c-0deb1185e58d = { name = "TupleArrays", path = "T/TupleArrays" }
940161ba-3fd6-11eb-2543-03b21f658be9 = { name = "UtilsGJL", path = "U/UtilsGJL" }
a80a13f6-0846-40c3-b505-f91c1b821ec1 = { name = "PairTools", path = "P/PairTools" }
c4c67b59-b612-4a28-8b47-1c875e8dafd5 = { name = "Phase4s", path = "P/Phase4s" }
c5e1564c-46d0-4d88-984f-9aacba45ce63 = { name = "Qurt", path = "Q/Qurt" }
c81f731e-df55-41db-9e3a-d20e2eda289e = { name = "InterfaceTraits", path = "I/InterfaceTraits" }
d1730f61-8521-49b5-9a1a-56a32d208dc4 = { name = "BitsX", path = "B/BitsX" }
da1032b5-7410-4fe7-baa6-5cca8121c0cc = { name = "ControlFlow", path = "C/ControlFlow" }
dc918f9c-79cc-42e6-85f1-d8b9b09632f4 = { name = "StreamToString", path = "S/StreamToString" }
e8637a5f-fa46-429a-85d3-62b6b7f83b1f = { name = "QMatrices", path = "Q/QMatrices" }
f4485a06-ee1a-4e97-a8d5-fc032a1b0f3c = { name = "QIBase", path = "Q/QIBase" }
